# Generated by Django 6.0.6 on 2026-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_shorturl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
